property/urls.py
from django.urls import path
from property.views import (
    Home,
    PostPropertyView,
    UpdatePropertyView,
    PropertyDetailView,
    PropertyRequestList,
    RequestResponseView,
    BookingList,
    UpdateRequest,
    LeaveProperty,
    UpdateRequestResponseView,
    ConfirmBookingView,
    GenerateAgreementPdfView,
)


urlpatterns = [
    path("home/", Home.as_view(), name="home"),
    path("post/", PostPropertyView.as_view(), name="post_property"),
    path(
        "update/<int:property_id>/",
        UpdatePropertyView.as_view(),
        name="update_property",
    ),
    path(
        "detail/<int:property_id>/",
        PropertyDetailView.as_view(),
        name="property_detail",
    ),
    path("requests/", PropertyRequestList.as_view(), name="property_requests"),
    path(
        "request-response/<int:pk>/",
        RequestResponseView.as_view(),
        name="request_response",
    ),
    path("bookings/", BookingList.as_view(), name="bookings"),
    path("update-request/<int:pk>/", UpdateRequest.as_view(), name="update_view"),
    path("leave/<int:pk>/", LeaveProperty.as_view(), name="leave_property"),
    path(
        "update-request-response/<int:pk>/",
        UpdateRequestResponseView.as_view(),
        name="update_request_response",
    ),
    path(
        "confirm-booking/<int:pk>/",
        ConfirmBookingView.as_view(),
        name="confirm_booking",
    ),
    path(
        "generate-agreement-pdf/<int:property_request_id>/",
        GenerateAgreementPdfView.as_view(),
        name="agreement_pdf",
    ),
]

rentify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from property.views import Home
from payment.views import my_webhook_view

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("user/", include("user.urls")),
    path("property/", include("property.urls")),
    path("rating/", include("rating.urls")),
    path("payment/", include("payment.urls")),
    path("admin/", admin.site.urls),
    path("webhook", my_webhook_view, name="webhook"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views

from user.views import SignupView, ViewProfile, UpdateProfile
from user.forms import UserProfileModelForm, AddressModelForm


urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(
            next_page=reverse_lazy("home"), template_name="user/login.html"
        ),
        name="login",
    ),
    path("signup/", SignupView.as_view(), name="signup"),
    path("profile/<int:user_id>/", ViewProfile.as_view(), name="profile"),
    path(
        "update-profile/<int:user_id>/", UpdateProfile.as_view(), name="update_profile"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="/user/login/"),
        name="logout",
    ),
    path(
        "change-password/",
        auth_views.PasswordChangeView.as_view(
            success_url="/user/login/", template_name="user/change_password.html"
        ),
        name="change_password",
    ),
    path("", include("django.contrib.auth.urls")),
]

property/models.py
from django.db import models
from user.models import UserProfile, BaseAddress
import uuid


class Property(models.Model):
    PROPERTY_TYPES_CHOICES = (
        ("apartment", "Apartment"),
        ("house", "House"),
        ("flat_1bkh", "Flat-1bhk"),
        ("flat_2bkh", "Flat-2bhk"),
        ("flat_3bkh", "Flat-3bhk"),
    )
    owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, null=True)
    property_type = models.CharField(
        max_length=20, choices=PROPERTY_TYPES_CHOICES, default="house"
    )
    is_available = models.BooleanField(default=True)
    availability_date = models.DateField(blank=True, null=True)
    rent_amount = models.PositiveIntegerField()
    description = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.name} {self.property_type}"

    def save(self, *args, **kwargs):
        """
            updating responsed rent amount if rent amount is changed by owner
            if booking not confirmed by renter
        """
        status_choice = PropertyRequestResponse.STATUS_CHOICES
        property_request_response = PropertyRequestResponse.objects.filter(status=status_choice[1][0], request_response_property=self, user__user_type='owner')
        property_request_response.update(rent_amount=self.rent_amount)
        super().save(*args, **kwargs)


class PropertyAddress(BaseAddress):
    property = models.OneToOneField(Property, on_delete=models.CASCADE)


class PropertyImage(models.Model):
    """
    model to store images of property
    """

    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="property_images")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Amenity(models.Model):
    """
    stores amenity of property
    """

    STATUS_CHOICES = (
        ("available", "Available"),
        ("unavailable", "Unavailable"),
        ("maintenance", "Under Maintenance"),
    )
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default="available"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class PropertyRequestResponse(models.Model):
    """
    stores renter's request to property and owner's response to property
    here user is person who requests or response

    request Token of request sent by renter and response by owner on renter's request
    will be Same
    """

    STATUS_CHOICES = (
        ("processing", "Processing"),
        ("responsed", "Responsed"),
        ("rejected", "Rejected"),
        ("approved", "Approved"),
        ("left", "Lefted"),
    )
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default="processing"
    )
    request_token = models.CharField(default=uuid.uuid4, max_length=36)
    user = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True)
    request_response_property = models.ForeignKey(
        Property, on_delete=models.SET_NULL, null=True
    )
    rent_amount = models.PositiveIntegerField(null=True)
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            "request_token",
            "user",
            "request_response_property",
            "created_at",
        )

    @property
    def renter(self):
        return PropertyRequestResponse.objects.get(
            user__user_type="renter", request_token=self.request_token
        ).user


class Booking(models.Model):
    """DateTimeField
    stores Property booking by renter
    """

    property_request_response = models.OneToOneField(
        PropertyRequestResponse, on_delete=models.CASCADE, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def renter(self):
        request_token = self.property_request_response.request_token
        property_request_response = PropertyRequestResponse.objects.get(
            request_token=request_token, user__user_type="renter"
        )
        return property_request_response.user


class Agreement(models.Model):
    """
    stores agreement between owner and renter
    """

    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    document = models.FileField(upload_to="aggrement/renter")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

property/forms.py
from django import forms
from django.core.exceptions import ValidationError

from user.models import Location
from property.models import (
    Property,
    PropertyAddress,
    PropertyImage,
    Agreement,
    PropertyRequestResponse,
    Amenity,
)


class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        exclude = ["address"]
        widgets = {
            "owner": forms.HiddenInput(),
            "availability_date": forms.widgets.DateInput(attrs={"type": "date"}),
        }


class ProprtyImageModelForm(forms.ModelForm):
    class Meta:
        model = PropertyImage
        fields = ["image"]
        widgets = {"image": forms.FileInput(attrs={"id": "image_input"})}


class AddressModelForm(forms.ModelForm):
    postal_code = forms.CharField()

    class Meta:
        model = PropertyAddress
        fields = ["postal_code", "street_address"]

    def clean_postal_code(self):
        postal_code = self.cleaned_data["postal_code"]
        location = Location.objects.filter(postal_code=postal_code)

        if location.exists():
            return location.first()
        else:
            raise ValidationError("Pincode does not exists.")


class AmenityModelForm(forms.ModelForm):
    class Meta:
        model = Amenity
        fields = ["name", "status"]


class RequestPropertyModelForm(forms.ModelForm):
    class Meta:
        model = PropertyRequestResponse
        fields = ["start_date", "end_date", "rent_amount"]
        widgets = {
            "start_date": forms.widgets.DateInput(attrs={"type": "date"}),
            "end_date": forms.widgets.DateInput(attrs={"type": "date"}),
        }


class PropertyRequestResponseForm(forms.ModelForm):
    class Meta:
        model = PropertyRequestResponse
        exclude = ["user", "property", "status", "request_response_property"]
        labels = {"rent_amount": "Requested rent amount", "document": "sent aggrement"}
        widgets = {
            "start_date": forms.widgets.DateInput(attrs={"type": "date"}),
            "end_date": forms.widgets.DateInput(attrs={"type": "date"}),
            "request_token": forms.HiddenInput(),
        }


class AgreementModelForm(forms.ModelForm):
    class Meta:
        model = Agreement
        fields = ["document"]
        labels = {"document": "sent aggrement"}
        help_texts = {
            "document": "Upload agreement after doing signature on agreement send by owner",
        }

property/templates/property/current_booking.html
{% for booking in booking_list %}
    <div style="margin: 40px 10px 0px 10px;border: 2px solid blue;display : flex;flex-direction : row;">
        <div style="border: 2px solid yellow;width: 30%;">
            {% for property in booking.property_request_response.request_response_property.propertyimage_set.all %}    
                {%  if forloop.counter == 1 %}    
                    <img style="width: 90%;height: 90%;padding: 2px;" src="{{property.image.url}}" alt="Image not available" />
                {% endif %}
            {% empty %}
                <h5>Image not available</h5>
            {% endfor %}
        </div>
        <div style="border: 2px solid red;width: 80%;padding: 5px;">
            <h4 >Name:  {{booking.property_request_response.request_response_property.name|default:"not available"}} </h4>
            <h4 >Address: {{booking.property_request_response.request_response_property.propertyaddress.full_address|default:"not available"}} </h4>
            <h4 >Type: {{booking.property_request_response.request_response_property.property_type|default:"not available"}}</h4>            
            <h4>Rented amount : {{booking.property_request_response.rent_amount}}</h4>
            <h4>Requested date : {{booking.property_request_response.created_at.date}}</h4>
            <h4>Start date :{{booking.property_request_response.start_date}}</h4>
            <h4>End date :{{booking.property_request_response.end_date|default:" not available"}}</h4>
            <h4>Approved date : {{booking.created_at.date}}
            {% if request.user.user_type == "renter" %}
                <h4>Owner name : {{booking.property_request_response.request_response_property.owner.get_full_name|default:"Not available"}}</h4>
                <h4>Contact number : {{ booking.property_request_response.request_response_property.owner.phone_number}}</h4>
                <h4>Status : {{booking.property_request_response.status}}</h4>
            {% else %}
                <h4>Renter name : {{booking.renter.get_full_name|default:"not available"}}</h4>
                <h4>Contact number : {{booking.renter.phone_number}}</h4>
            {% endif %}
        </div>
    </div>
    {% if booking_history != 'true' %}
        <div class="review_rating_div" data-csrf_token={{csrf_token}} data-booking_id="{{booking.id}}" >
            {% if request.user.user_type == 'renter' %}
                <div class = "property-rating-review">
                    <div id='rating-div'  style="width: 100%;padding: 5px;margin:5px;display: flex;justify-content: center;align-items: center;">
                        <span class="property-rating-{{booking.id}} property-rating fa fa-star star-{{booking.id}}-1 {% if booking.propertyrating.rating >= 1 %} checked {% endif %}" data-star="1" data-booking_id="{{booking.id}}"></span>
                        <span class="property-rating-{{booking.id}} property-rating fa fa-star star-{{booking.id}}-2 {% if booking.propertyrating.rating >= 2 %} checked {% endif %}" data-star="2" data-booking_id="{{booking.id}}"></span>
                        <span class="property-rating-{{booking.id}} property-rating fa fa-star star-{{booking.id}}-3 {% if booking.propertyrating.rating >= 3 %} checked {% endif %}" data-star="3" data-booking_id="{{booking.id}}"></span>
                        <span class="property-rating-{{booking.id}} property-rating fa fa-star star-{{booking.id}}-4 {% if booking.propertyrating.rating >= 4 %} checked {% endif %}" data-star="4" data-booking_id="{{booking.id}}"></span>
                        <span class="property-rating-{{booking.id}} property-rating fa fa-star star-{{booking.id}}-5 {% if booking.propertyrating.rating == 5 %} checked {% endif %}" data-star="5" data-booking_id="{{booking.id}}"></span>  
                    </div>
                    <div style="display: flex;justify-content: center;align-items: center;">
                        <form class="review_form-{{booking.id}}" method="post" action="#">
                            <h4 id="property_review_{{booking.id}}">
                                Your review : 
                                {{booking.propertyreview.description|default:'No review'}}
                            </h4>
                            {% csrf_token %}
                            <label for="id_description">Review:</label>
                            <input type="text" name="description" value="{{booking.propertyreview.description}}" maxlength="50" required id="id_description">
                            <input class="submit_property_review" type="button" value="{% if booking.propertyreview.description %} change {% else %} submit {% endif %}" data-booking_id="{{booking.id}}" >
                        </form>
                    </div>
                </div>
            {% else %}
                <div style="padding: 5px;margin:5px;display: flex;justify-content: center;align-items: center;">
                    <a href="/payment/bills/{{booking.id}}/" >View and send Bills<a>
                </div>
                <div class = "renter-rating-review">
                    <div id='rating-div'  style="border: 2px solid blue;width: 100%;padding: 5px;margin:5px;display: flex;justify-content: center;align-items: center;">
                        <span class="renter-rating-{{booking.id}} renter-rating fa fa-star star-{{booking.id}}-1 {% if booking.renterrating.rating >= 1 %} checked {% endif %}" data-star="1" data-booking_id="{{booking.id}}"></span>
                        <span class="renter-rating-{{booking.id}} renter-rating fa fa-star star-{{booking.id}}-2 {% if booking.renterrating.rating >= 2 %} checked {% endif %}" data-star="2" data-booking_id="{{booking.id}}"></span>
                        <span class="renter-rating-{{booking.id}} renter-rating fa fa-star star-{{booking.id}}-3 {% if booking.renterrating.rating >= 3 %} checked {% endif %}" data-star="3" data-booking_id="{{booking.id}}"></span>
                        <span class="renter-rating-{{booking.id}} renter-rating fa fa-star star-{{booking.id}}-4 {% if booking.renterrating.rating >= 4 %} checked {% endif %}" data-star="4" data-booking_id="{{booking.id}}"></span>
                        <span class="renter-rating-{{booking.id}} renter-rating fa fa-star star-{{booking.id}}-5 {% if booking.renterrating.rating == 5 %} checked {% endif %}" data-star="5" data-booking_id="{{booking.id}}"></span>
                    </div>
                    <div style="display: flex;justify-content: center;align-items: center;">
                        <form class="review_form-{{booking.id}}" method="post" action="#">
                            <h4 id="renter_review_{{booking.id}}">
                                Your review : 
                                {{booking.renterreview.description|default:'No review'}}
                            </h4>
                            {% csrf_token %}
                            <label for="id_description">Review:</label>
                            <input type="text" name="description" value="{{booking.renterreview.description}}" maxlength="50" required id="id_description">
                            <input class="submit_renter_review" type="button" value="{% if booking.renterreview.description %} change {% else %} submit {% endif %}" data-booking_id="{{booking.id}}">
                        </form>
                    </div>
                <div>
            {% endif %}
        </div>
        <div style="border: 2px solid yellow;width: 100%;padding: 5px;display: flex;justify-content: center;align-items: center;">
            
            <a href='/property/leave/{{booking.property_request_response.request_response_property.id}}/'>
                <button >
                    {% if request.user.user_type == "owner" %}
                        Remove renter
                    {% else %}
                        Leave property
                    {% endif %}
                </button>
            </a>
        </div>
    {%endif%}
{% empty %}
    <div style="border: 2px solid yellow;width: 100%;padding: 50px 5px 50px 5px;display: flex;justify-content: center;align-items: center;">
        <h3>
            {% if booking_history == 'true' %}
                No history Bookings
            {% else %}
                No current Bookings
            {% endif %}
        </h3>
    </div>
{% endfor %}
{{form}}

property/templates/property/home.html
{% extends "user/base.html" %}
{% load static %}
{% block home %}
    <li><a class="nav-link scrollto active" href="{% url 'home' %}">Home</a></li>
    {% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'css/home.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
{% endblock %}

{% block content %}
    <div id="parent_div">
        <div id ="search_div">        
            <div class="search-box">
                <form method="GET">
                    <button type='submit' class="btn-search"><i class="fas fa-search"></i></button>
                    <input id="search_button" name="search" type="text" class="input-search" placeholder="Search by properyt name, location ...">
                </form>
            </div>

            {% if search %}
                <div id="search_div">
                    <p >Showing result for search : {{search}}<p>
                </div>
            {% endif %}
        </div>
    </div>
    <div style="margin-top:{% if search %}95px {% else %}55px{% endif %};">
        <div id="side_bar_div">
            <h4 style="padding:10px;">Filter by :</h4>
            <div class="range_container">
                <h4>Price range</h4>
                <div class="sliders_control" >
                    <input id="fromSlider" type="range" value="{{min_price|default:1000}}" min="500" max="95000"/>
                    <input id="toSlider" type="range" value="{{max_price|default:50000}}" min="0" max="100000"/>
                    <form id="price_range_filter" action="" method="GET" style="display:inline-block">
                        <div  style="display:inline-block"class="form_control_container">
                            <div class="form_control_container__time">Min Price</div>
                            <input name="min_price" class="form_control_container__time__input" type="number" id="fromInput" value="{{min_price|default:1000}}" min="500" max="95000"/>
                        </div>
                        <div style="display:inline-block" class="form_control_container">
                            <div class="form_control_container__time">Max Price</div>
                            <input name="max_price" class="form_control_container__time__input" type="number" id="toInput" value="{{max_price|default:50000}}" min="500" max="100000"/>
                        </div>
                        {% if search %}
                            <input type="hidden" name='search' value={{search}} >
                        {% endif %}
                        {% if property_type %}
                            <input type="hidden" name='property_type' value={{property_type}} >
                        {% endif %}
                        <div style="margin-top:10px;">
                            <h4>Property type</h4>
                            <input type="radio" id="all" name="property_type" value="all" {% if property_type == 'all' or not property_type %} checked{% endif %}>
                            <label for="all">All</label><br>
                            <input type="radio" id="house" name="property_type" value="house" {% if property_type == 'house' %} checked {% endif %}>
                            <label for="house">House</label><br>
                            <input type="radio" id="apartment" name="property_type" value="apartment" {% if property_type == 'apartment' %} checked {% endif %}>
                            <label for="apartment">Apartment</label><br>
                            <input type="radio" id="flat_1bkh" name="property_type" value="flat_1bkh" {% if property_type == 'flat_1bkh' %} checked {% endif %}>
                            <label for="flat_1bkh">Flat-1bhk</label><br>
                            <input type="radio" id="flat_2bkh" name="property_type" value="flat_2bkh" {% if property_type == 'flat_2bkh' %} checked {% endif %}>
                            <label for="flat_2bkh">Flat-2bhk</label><br>
                            <input type="radio" id="flat_3bkh" name="property_type" value="flat_3bkh" {% if property_type == 'flat_3bkh' %} checked {% endif %}>
                            <label for="flat_3bkh">Flat-3bhk</label>
                        </div>
                    <div id="filter_button">
                        <a href="{% url 'home' %}">
                            <input type="button" value="Clear search and filter">
                        </a>
                        <input type="submit" value="Filter">
                    </div>
                </form>
                </div>
            </div>
            
                
                
            
        </div>
        <div style="min-height:300px;margin-top:50px;margin-left:370px;{% if not property %} display: flex;justify-content: center;align-items: center;{% endif %}">
            {% for property in property %}
                <div style="margin: 40px 10px 0px 10px;border: 2px solid blue;display : flex;flex-direction : row;">
                    <div style="border: 2px solid yellow;width: 30%;">
                        {% for property in property.propertyimage_set.all %}
                            {%  if forloop.counter == 1 %}
                                <img style="width: 90%;height: 90%;padding: 2px;" src="{{property.image.url}}" alt="Image not available" />
                            {% elif forloop.counter < 6 %} 
                            <img style="width: 10%;height: 10%;padding: 2px;" src="{{property.image.url}}" alt="Image not available" />

                            {% endif %}
                        {% empty %}
                            <h5>Image not available</h5>
                        {% endfor %}
                    </div>
                    <div style="border: 2px solid red;width: 80%;padding: 5px;">
                        <h4 >Name:  {{property.name|default:"not available"}} </h4>
                        <h4 >Address: {{property.propertyaddress.full_address|default:"not available"}} </h4>
                        <h4 >Type: {{property.property_type|default:"not available"}}</h4>
                        <h4>Rent amount : ₹ {{property.rent_amount}} </h4>
                        <h4>Property Ratings : 
                            <span class="fa fa-star {% if property.rating >= 1 %} checked {% endif %}"></span>
                            <span class="fa fa-star {% if property.rating >= 2 %} checked {% endif %}"></span>
                            <span class="fa fa-star {% if property.rating >= 3 %} checked {% endif %}"></span>
                            <span class="fa fa-star {% if property.rating >= 4 %} checked {% endif %}"></span>
                            <span class="fa fa-star {% if property.rating == 5 %} checked {% endif %}"></span>
                        </h4>
                    </div>
                        <button >
                            {% if request.user.user_type == "owner" %}
                                <a href="{% url 'update_property' property_id=property.id %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                                        <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                                    </svg>
                                    Edit
                                </a>
                            {% else %}
                                <a href="{% url 'property_detail' property_id=property.id %}">
                                    <i class="bi bi-arrow-right"></i><br>
                                    See detail
                                </a>    
                            {% endif %}
                        </button>
                    
                </div>
            {% empty %}
                <h3>No result found</h3>
            {% endfor %}
        </div>
    </div>

    <div  style="display: flex;justify-content: center;align-items: center;" class="pagination">
        <span style="" class="step-links">
            {% if property.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ property.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ property.number }} of {{ property.paginator.num_pages }}.
            </span>
    
            {% if property.has_next %}
                <a href="?page={{ property.next_page_number }}">next</a>
                <a href="?page={{ property.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div> 

    <script src="{% static 'js/home.js' %}"></script>
{% endblock %}

property/templates/property/property_detail.html
{% extends "user/base.html" %}
{% load static %} 
{% block css %}
    {{block.super}}
    <link href="{% static 'css/property_detail.css' %}" rel="stylesheet">
{% endblock %}

{% block js %}
    {{block.super}}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
    <div style="border: 1px solid blue;padding: 5px;">

        <div align="center"  id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                {% for property in property.propertyimage_set.all %}
                    <div style="background-color:#f1ecec" class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
                        <img style="width: auto;height: 700px;padding: 2px;" src="{{property.image.url}}" alt="Image not available" />
                    </div>
                {% empty %}
                    <h5>Image not available</h5>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div style="display:flex;justify-content: center;align-items: center;border: 2px solid red;">
        <div style="width: 50%;padding: 5px;">
            <h3>Name : {{property.name}}</h3>
            <h3>Address : {{property.propertyaddress.full_address}}</h3>
            <h3>Type : {{property.property_type}}</h3>
            <h3>Rent amount : {{property.rent_amount}}</h3>
            <h3>Owner name : {{property.owner.get_full_name|default:"Not available"}}</h3>
            <h3>Contact number : {{ property.owner.phone_number}}</h3>
            <h3>Amenity :
                {% for amenity in property.amenity_set.all %}
                    {{amenity.name}} - {{amenity.status}},
                {% empty %}
                    Not added by owner
                {% endfor %}
        </div>
        <div style="width:50%;padding: 15px;">
            <form method="post">
                {% csrf_token %}
                <div >
                    <h2 >Request Property</h2>
                    {{request_property_form.as_p}}
                    <input type="submit" value="request">
                </div>
            </form>
        </div>
    </div>

{% endblock %}