payment/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from payment.views import (
    BookingBillView,
    AllBookingBillView,
    PayBillView,
    create_checkout_session,
)
from django.views.generic.base import TemplateView

urlpatterns = [
    path("all-bills/", AllBookingBillView.as_view(), name="all_bills"),
    path("bills/<int:booking_id>/", BookingBillView.as_view(), name="booking_bills"),
    path("pay-bill/<int:bill_id>/", PayBillView.as_view(), name="pay_bill"),
    path(
        "api/checkout-session/<int:bill_id>/",
        create_checkout_session,
        name="api_checkout_session",
    ),
    path(
        "payment-success/",
        TemplateView.as_view(template_name="payment/payment_success.html"),
        name="payment_success",
    ),
    path(
        "payment-fail/",
        TemplateView.as_view(template_name="payment/payment_fail.html"),
        name="payment_fail",
    ),
]

rentify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from property.views import Home
from payment.views import my_webhook_view

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("user/", include("user.urls")),
    path("property/", include("property.urls")),
    path("rating/", include("rating.urls")),
    path("payment/", include("payment.urls")),
    path("admin/", admin.site.urls),
    path("webhook", my_webhook_view, name="webhook"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views

from user.views import SignupView, ViewProfile, UpdateProfile
from user.forms import UserProfileModelForm, AddressModelForm


urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(
            next_page=reverse_lazy("home"), template_name="user/login.html"
        ),
        name="login",
    ),
    path("signup/", SignupView.as_view(), name="signup"),
    path("profile/<int:user_id>/", ViewProfile.as_view(), name="profile"),
    path(
        "update-profile/<int:user_id>/", UpdateProfile.as_view(), name="update_profile"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="/user/login/"),
        name="logout",
    ),
    path(
        "change-password/",
        auth_views.PasswordChangeView.as_view(
            success_url="/user/login/", template_name="user/change_password.html"
        ),
        name="change_password",
    ),
    path("", include("django.contrib.auth.urls")),
]

payment/models.py
from django.db import models
from property.models import Booking, UserProfile

# Create your models here.


class Bill(models.Model):
    """
    stores bills of property booking
    """

    BILL_STATUS_CHOICES = (
        ("paid", "Paid"),
        ("partial_paid", "Partially paid"),
        ("not_paid", "Not paid"),
    )
    MONTH_CHOICES = (
        ("jan", "January"),
        ("feb", "February"),
        ("mar", "March"),
        ("Apr", "April"),
        ("may", "May"),
        ("jun", "June"),
        ("jul", "July"),
        ("aug", "August"),
        ("sep", "September"),
        ("oct", "Octomber"),
        ("nov", "November"),
        ("dec", "December"),
    )
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()
    status = models.CharField(choices=BILL_STATUS_CHOICES, max_length=20)
    document = models.FileField(upload_to="bills", null=True)
    month = models.CharField(
        choices=MONTH_CHOICES, max_length=3, default=BILL_STATUS_CHOICES[2][0]
    )
    year = models.PositiveIntegerField(null=True)
    due_date = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def paid_amount(self):
        paid_amount = Payment.objects.filter(bill=self, status="success").aggregate(
            models.Sum("amount")
        )
        paid_amount = (
            paid_amount["amount__sum"] if paid_amount["amount__sum"] != None else 0
        )
        return paid_amount


class Payment(models.Model):
    """
    stores payment by renter for a booking
    """

    bill = models.ForeignKey(Bill, on_delete=models.CASCADE)
    user = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True)
    amount = models.PositiveIntegerField()
    source = models.CharField(max_length=20)
    status = models.CharField(max_length=20)
    checkout_session_id = models.CharField(max_length=100, null=True)
    payment_intent = models.CharField(max_length=100, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

payment/forms.py
from django import forms

from payment.models import Bill, Payment


class BillModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BillModelForm, self).__init__(*args, **kwargs)
        self.fields["document"].required = False

    class Meta:
        model = Bill
        fields = "__all__"
        widgets = {
            "amount": forms.HiddenInput(),
            "booking": forms.HiddenInput(),
            "status": forms.HiddenInput(),
            "document": forms.HiddenInput(),
            "due_date": forms.widgets.DateInput(attrs={"type": "date"}),
        }


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ["amount"]

payment/views.py
from django.shortcuts import render
from django.views import View

from weasyprint import HTML, CSS
from django.template.loader import get_template
from django.http import HttpResponse, HttpResponseNotFound

# Create your views here.
from django.template.loader import render_to_string
from django.shortcuts import get_object_or_404

from django.db.models import Q, F, Sum

from django.utils import timezone

from payment.models import Bill, Payment
from payment.forms import BillModelForm, PaymentForm
from payment.utility import generate_pdf
from property.models import Booking, PropertyRequestResponse

from user.models import UserProfile

from django.core.files.uploadedfile import SimpleUploadedFile
from django.shortcuts import render, redirect
from django.urls import reverse
from django.db.models import Q, Subquery

import stripe
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from django.conf import settings


class AllBookingBillView(View):
    
    def get(self, request, *args, **kwargs):
        user_id = self.request.user.id
        bookings = Booking.objects.filter(
            property_request_response__request_token__in=Subquery(
                PropertyRequestResponse.objects.filter(user__id=user_id).values(
                    "request_token"
                )
            ),
        ).order_by("created_at")

        return render(request, "payment/bills.html", {"bookings": bookings})


class BookingBillView(View):
    """
    bill for particular booking, only for owner
    """

    template_name = "payment/booking_bills.html"
    form_class = BillModelForm
    bill_status = Bill.BILL_STATUS_CHOICES
    month_choice = Bill.MONTH_CHOICES
    current_time = timezone.now()

    def calculate_bill(self, request, booking_id, bill_data_dict):
        past_due_amount = self.past_due_bill(booking_id)
        context_data = {"past_due_amount": past_due_amount}
        context_data.update(bill_data_dict)
        bill_pdf = generate_pdf(request, "payment/generate_bill.html", context_data)
        return bill_pdf

    def past_due_bill(self, booking_id):
        due_bills = Bill.objects.filter(
            ~Q(status=self.bill_status[0][0]), booking_id=booking_id
        ).annotate(
            due_amount=F("amount")
            - Sum("payment__amount", filter=Q(payment__status="success"))
        )
        total_due_amount = due_bills.aggregate(Sum("due_amount"))
        return total_due_amount["due_amount__sum"]

    def get(self, request, *args, **kwargs):
        booking_id = kwargs["booking_id"]
        booking = get_object_or_404(Booking, pk=booking_id)
        bills = Bill.objects.filter(booking_id=booking_id)
        current_bill_amount = PropertyRequestResponse.objects.get(
            booking__id=booking_id, user__user_type="owner"
        ).rent_amount

        current_month = self.current_time.strftime("%B").lower()[:3]
        current_year = self.current_time.year
        initail_data = {
            "booking": booking,
            "status": self.bill_status[2][0],
            "month": current_month,
            "year": current_year,
            "amount": current_bill_amount,
        }
        context = {
            "bill_form": self.form_class(initial=initail_data),
            "bills": bills,
            "booking": booking,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        bill_form = self.form_class(request.POST)
        booking_id = kwargs["booking_id"]
        booking = get_object_or_404(Booking, pk=booking_id)

        if bill_form.is_valid():
            due_date = bill_form.cleaned_data["due_date"]
            month = bill_form.cleaned_data["month"]
            year = bill_form.cleaned_data["year"]
            current_bill_amount = bill_form.cleaned_data["amount"]
            bill_data_dict = {
                "due_date": due_date,
                "month": month,
                "year": year,
                "current_bill_amount": current_bill_amount,
                "current_time": self.current_time,
                "booking": booking,
            }
            bill_pdf = self.calculate_bill(request, booking_id, bill_data_dict)
            file_name = (
                f"{str(year)}-{ str(month) }-{ booking.renter.get_full_name() }.pdf"
            )
            bill_form.instance.document = SimpleUploadedFile(
                file_name, bill_pdf, content_type="application/pdf"
            )
            bill_form.save()
            return redirect(reverse("booking_bills", args=[booking_id]))
        else:
            print("-->", bill_form.errors)

        bills = Bill.objects.filter(booking_id=booking_id)
        context = {"bill_form": bill_form, "bills": bills, "booking": booking}
        return render(request, self.template_name, context)


class PayBillView(View):
    template_name = "payment/pay_bill.html"
    form_class = PaymentForm

    def get(self, request, *args, **kwargs):
        bill_id = kwargs["bill_id"]
        bill = Bill.objects.get(id=bill_id)
        payable_amount = bill.amount - bill.paid_amount
        initail_data = {"amount": payable_amount}
        payment_form = self.form_class(initial=initail_data)
        context = {
            "payment_form": payment_form,
            "stripe_publishable_key": settings.STRIPE_PUBLISHABLE_KEY,
            "bill_id": bill_id,
        }
        return render(request, self.template_name, context)


@csrf_exempt
def create_checkout_session(request, bill_id):
    request_data = json.loads(request.body)
    paying_amount = int(request_data["paying_amount"])
    stripe.api_key = settings.STRIPE_SECRET_KEY
    checkout_session = stripe.checkout.Session.create(
        payment_method_types=["card"],
        line_items=[
            {
                "price_data": {
                    "currency": "INR",
                    "product_data": {
                        "name": "test",
                    },
                    "unit_amount": int(paying_amount * 100),
                },
                "quantity": 1,
            }
        ],
        metadata={
            "paying_amount": paying_amount,
            "user_id": request.user.id,
            "bill_id": bill_id,
        },
        mode="payment",
        success_url=request.build_absolute_uri(reverse("payment_success")),
        cancel_url=request.build_absolute_uri(reverse("payment_fail")),
    )
    return JsonResponse({"sessionId": checkout_session.id})


@csrf_exempt
def my_webhook_view(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    payload = request.body
    sig_header = request.META["HTTP_STRIPE_SIGNATURE"]
    event = None
    endpoint_secret = settings.ENDPOINT_SECRET

    try:
        event = stripe.Webhook.construct_event(payload, sig_header, endpoint_secret)
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    if event["type"] == "checkout.session.completed":
        session = event["data"]["object"]

        paid_amount = int(session["metadata"]["paying_amount"])
        user_id = int(session["metadata"]["user_id"])
        bill_id = int(session["metadata"]["bill_id"])
        session_id = session["id"]
        payment_intent = session["payment_intent"]

        fulfill_order(user_id, bill_id, paid_amount, session_id, payment_intent)

    return HttpResponse(status=200)


def fulfill_order(user_id, bill_id, paying_amount, session_id, payment_intent):
    bill = Bill.objects.get(id=bill_id)
    status_choices = Bill.BILL_STATUS_CHOICES
    user = UserProfile.objects.get(id=user_id)
    payable_amount = bill.amount - bill.paid_amount

    if paying_amount >= payable_amount:
        # status = "paid"
        status = status_choices[0][0]
    else:
        # status = "partial_paid"
        status = status_choices[1][0]

    bill.status = status
    Payment.objects.create(
        user=user,
        bill=bill,
        amount=paying_amount,
        source="stripe",
        status="success",
        checkout_session_id=session_id,
        payment_intent=payment_intent,
    )
    bill.save()

payment/templates/payment/bills.html
{% extends "user/base.html" %}
{% load static %}
{% load mathfilters %}
{% block bill %}
    <li><a class="nav-link scrollto active" href="{% url 'all_bills' %}">Bills</a></li>
    {% endblock %}

{% block css %}
    <link href="{% static 'css/booking_bills.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class='main'>
        <table class="table table-bordered">
            <thead>
              <tr>
                <th scope="col">Booking</th>
                {% if request.user.user_type == 'renter' %}
                    <th scope="col">Owner</th>
                {% else %}
                    <th scope="col">Renter</th>
                {% endif %}
                <th scope="col">Phone</th>
                <th scope="col">Year</th>
                <th scope="col">Month</th>
                <th scope="col">Amount</th>
                <th scope="col">Paid Amount</th>
                <th scope="col">Remaining Amount</th>
                <th scope="col">Status</th>
                <th scope="col">Bill</th>
              </tr>
            </thead>
            <tbody>
                {% for booking in bookings %}
                        {% for bill in booking.bill_set.all %}
                        <tr>
                            <td>
                                <a href="{% url 'bookings' %}">
                                {{booking.property_request_response.request_response_property.name}}
                                </a>
                            </td>
                            {% if request.user.user_type == 'renter' %}
                                <td>{{booking.property_request_response.request_response_property.owner.get_full_name|default:"Not available"}}</td>
                                <td>{{ booking.property_request_response.request_response_property.owner.phone_number}}</td>
                            {% else %}
                                <td>{{booking.renter.get_full_name|default:"not available"}}</td>
                                <td>{{booking.renter.phone_number}}</td>
                            {% endif %}   
                            <td>{{bill.year}}</td>
                            <td>{{bill.month}}</td>
                            <td>{{bill.amount}}</td>
                            <td>{{bill.paid_amount|default:0}}</td>
                            <td>{{ bill.amount|sub:bill.paid_amount|default:bill.amount }}
                                {% if bill.status != 'paid' %}
                                    <a href="/payment/pay-bill/{{bill.id}}/">(Paynow)</a>
                                {% endif %}
                            </td>
                            <td>{{bill.status}}
                                
                            </td>
                            <td>
                                <a href="{{bill.document.url}}" target="_blank">bill</a>
                            </td>
                        <tr>
                        {% endfor %}
                {% endfor %}                
            </tbody>
        </table>
    </div>
{% endblock content %}

payment/templates/payment/booking_bills.html
{% extends "user/base.html" %}
{% load static %}
{% block bill %}
    <li><a class="nav-link scrollto active" href="{% url 'all_bills' %}">Bills</a></li>
    {% endblock %}

{% block css %}
    <link href="{% static 'css/booking_bills.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    
    <div class="main">
        <div>
            <div>
                <h3>Generate bill
            </div>
            <div class="bill_div">
                <h4>Property : {{booking.property_request_response.request_response_property.name|default:"Not available"}}</h4>
                {% if request.user.user_type == "renter" %}
                    <h4>Owner name : {{booking.property_request_response.request_response_property.owner.get_full_name|default:"Not available"}}</h4>
                {% else %}
                    <h4>Renter name : {{booking.renter.get_full_name|default:"not available"}}</h4>
                    <h4>Contact number : {{booking.renter.phone_number}}</h4>
                {% endif %}
            </div>
            <div>
                <form method='post'>
                    {% csrf_token %}
                    {{bill_form.as_p}}
                    <input type='submit' value='Generate' >
                </form>
            </div>
        </div>
        
    </div>
    <div>
        <table class="table table-bordered">
            <thead>
              <tr>
                <th scope="col">Year</th>
                <th scope="col">Month</th>
                <th scope="col">Amount</th>
                <th scope="col">Status</th>
                <th scope="col">Bill</th>
              </tr>
            </thead>
            <tbody>
                {% for bill in bills %}
                    <tr>
                        <td>{{bill.year}}</td>
                        <td>{{bill.month}}</td>
                        <td>{{bill.amount}}</td>
                        <td>{{bill.status}}</td>
                        <td>
                            <a href="{{bill.document.url}}" target="_blank">bill</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

payment/templates/payment/generate_bill.html
<!DOCTYPE html>
<html>
<head>
    <title>Rental Bill</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .address {
            margin-bottom: 0px;
            display : inline;
        }

        .address h2 {
            margin: 0;
        }

        .renter_address{
            width: 47%;
            float : left;

        }

        .owner_address{
            width: 47%;
            float : right;
        }

        .bill-details {
            margin-bottom: 20px;
            margin-top : 20px;
        }

        .bill-details table {
            width: 100%;
            border-collapse: collapse;
        }

        .bill-details th, .bill-details td {
            border: 1px solid #ccc;
            padding: 8px;
            text-align: left;
        }

        .total {
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Rental Bill ({{month}}) </h1>
            <p>Generate Date: {{ current_time|date:'D d M Y' }}</p>
            <p>Due Date: {{ due_date|date:'D d M Y' }}</p>
            
        </div>
        
        <!-- Owner's Address -->
        <div class="address">
            <div class="owner_address">
                <h2>Owner</h2>
                <p>{{booking.property_request_response.request_response_property.name|default:"not available"}},</p>
                <p>{{booking.property_request_response.request_response_property.propertyaddress.full_address|default:"not available"}},</p>
                <p>{{booking.property_request_response.request_response_property.owner.phone_number}}</p>
            </div>
            
            <!-- Renter's Address -->
            <div class="renter_address">
                <h2>Renter</h2>
                <p>{{booking.renter.get_full_name}},</p>
                <p>{{booking.renter.useraddress.full_address}},</p>
                <p>{{booking.renter.phone_number}}</p>
            </div>
        </div>

        <div class="bill-details">
            <table>
                <tr>
                    
                    <th>Description</th>
                    <th>Past Dues</th>
                    <th>Current bill Amount</th>
                    <th>Final Amount Due</th>
                </tr>
                <tr>
                    <td>{{ item1_description|default:'-' }}</td>
                    <td>{{ past_due_amount|default:0 }}</td>
                    <td>{{current_bill_amount}}</td>
                    <td>{{ past_due_amount|default:0 |add:current_bill_amount }}</td>
                    
                </tr>
               
            </table>
        </div>
        <div class="total">
            generated by : Rentify
        </div>
    </div>
</body>
</html>

payment/templates/payment/pay_bill.html
{% extends "user/base.html" %}
{% load static %}
{% load mathfilters %}
{% block bill %}
    <li><a class="nav-link scrollto active" href="{% url 'all_bills' %}">Bills</a></li>
    {% endblock %}

{% block css %}
    <link href="{% static 'css/pay_bill.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class='main'>
        <div class='payment_div' >
            
            <form class="payment_form">
                Total payable amount : {{payment_form.amount.value}}
                {{payment_form.as_p}}
                <input id="payment_button" type="button" value="Pay">
            </form>
        </div>
    </div>
    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">
        // Create an instance of the Stripe object with your publishable API key
        var stripe = Stripe('{{ stripe_publishable_key }}');
        var checkoutButton = document.getElementById('payment_button');
        var idInput = document.getElementById('id_amount'); 
        var bill_id = '{{ bill_id }}' ;

        checkoutButton.addEventListener('click', function () {

            // Create a new Checkout Session using the server-side endpoint you
            // created in step 3.
            paying_amount = idInput.value

            fetch("{% url 'api_checkout_session' bill_id=bill_id  %}", {
                method: 'POST',
                body: JSON.stringify(
                    { paying_amount: paying_amount
                        }
                )
            })
                .then(function (response) {
                    return response.json();
                })
                .then(function (session) {
                    return stripe.redirectToCheckout({ sessionId: session.sessionId });
                })
                .then(function (result) {
                    // If `redirectToCheckout` fails due to a browser or network
                    // error, you should display the localized error message to your
                    // customer using `error.message`.
                    if (result.error) {
                        alert(result.error.message);
                    }
                })
                .catch(function (error) {
                    console.error('Error:', error);
                });
        });
    </script>
    
{% endblock %}

payment/templates/payment/payment_fail.html
<html>
    <head>
        <title>
            Payment fail
        </title>
        <style>
            @import url(https://fonts.googleapis.com/css?family=Raleway:400,700,600);
.container{
  padding: 20px;
  display:flex;
  align-items:center;
}
body{
  background-color: #f6f4f4;
  font-family: 'Raleway', sans-serif;
}
.teal{
  background-color: #ffc952 !important;
  color: #444444 !important;
}
a{
  color: #47b8e0 !important;
}
.message{
  text-align: left;
}
.price1{
	font-size: 40px;
	font-weight: 200;
	display: block;
	text-align: center;
}
.ui.message p {margin: 5px;}
        </style>
    </head>
    <body>
    <div  class="container">
    <div class="ui middle aligned center aligned grid">
      <div class="ui eight wide column">
     
        <form class="ui large form">
                  
            <div class="ui icon negative message">
              <i class="warning icon"></i>
              <div class="content">
                <div class="header">
                  Oops! Something went wrong : payment failed
                </div>
              </div>
           </div>
            <span class="ui large teal submit fluid button"><a href="/property/home/">Home</a></span>
        </form>
      </div>
    </div>
  </div>
  <body>
</html>